# Generated by Django 5.0.7 on 2024-07-18 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherdata',
            name='user_id',
            field=models.CharField(max_length=255),
        ),
    ]
